tasks:
  - name: Create .env
    command: |
     echo HYPER=$INTRO_TO_GRAPHQL_HYPER >> .env
  - name: Install Deps
    init: |
      echo "⚡️ installing dependencies..."
      npm i
    command: |
      npm run dev
vscode:
  extensions:
    - graphql.vscode-graphql
    - marp-team.marp-vscode
    - standard.vscode-standard
ports:
  # Server
  - port: 4000
    onOpen: ignore
    visibility: public
